FROM golang:1.25.3-alpine

WORKDIR /app

RUN apk add --no-cache git

RUN go install github.com/air-verse/air@latest
RUN go install github.com/google/wire/cmd/wire@latest

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN wire ./cmd/http

EXPOSE 8080

CMD ["air", "-c", ".air.toml"]
