// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/marcelobritu/isayoga-api/internal/domain/repository"
	"github.com/marcelobritu/isayoga-api/internal/infrastructure/database"
	"github.com/marcelobritu/isayoga-api/internal/infrastructure/http/router"
	payment2 "github.com/marcelobritu/isayoga-api/internal/infrastructure/payment"
	"github.com/marcelobritu/isayoga-api/internal/infrastructure/repository/mongodb"
	"github.com/marcelobritu/isayoga-api/internal/interface/http/handler"
	"github.com/marcelobritu/isayoga-api/internal/usecase/class"
	"github.com/marcelobritu/isayoga-api/internal/usecase/enrollment"
	"github.com/marcelobritu/isayoga-api/internal/usecase/payment"
	"github.com/marcelobritu/isayoga-api/internal/usecase/user"
	"github.com/marcelobritu/isayoga-api/pkg/config"
	"go.mongodb.org/mongo-driver/mongo"
)

// Injectors from wire.go:

func InitializeServer() (*Server, error) {
	configConfig, err := config.Load()
	if err != nil {
		return nil, err
	}
	healthHandler := handler.NewHealthHandler()
	mongoDB, err := provideMongoDB(configConfig)
	if err != nil {
		return nil, err
	}
	database := provideMongoDatabase(mongoDB)
	userRepository := provideUserRepository(database)
	createUserUseCase := user.NewCreateUserUseCase(userRepository)
	getUserUseCase := user.NewGetUserUseCase(userRepository)
	listUsersUseCase := user.NewListUsersUseCase(userRepository)
	updateUserUseCase := user.NewUpdateUserUseCase(userRepository)
	deleteUserUseCase := user.NewDeleteUserUseCase(userRepository)
	userHandler := handler.NewUserHandler(createUserUseCase, getUserUseCase, listUsersUseCase, updateUserUseCase, deleteUserUseCase)
	client := provideMongoClient(mongoDB)
	classRepository := provideClassRepository(database, client)
	createClassUseCase := class.NewCreateClassUseCase(classRepository)
	listClassesUseCase := class.NewListClassesUseCase(classRepository)
	classHandler := handler.NewClassHandler(createClassUseCase, listClassesUseCase)
	enrollmentRepository := provideEnrollmentRepository(database)
	paymentRepository := providePaymentRepository(database)
	mercadoPagoClient := provideMercadoPagoClient(configConfig)
	enrollStudentUseCase := enrollment.NewEnrollStudentUseCase(classRepository, enrollmentRepository, paymentRepository, userRepository, mercadoPagoClient, configConfig)
	cancelEnrollmentUseCase := enrollment.NewCancelEnrollmentUseCase(enrollmentRepository, classRepository)
	enrollmentHandler := handler.NewEnrollmentHandler(enrollStudentUseCase, cancelEnrollmentUseCase)
	processWebhookUseCase := payment.NewProcessWebhookUseCase(paymentRepository, enrollmentRepository)
	webhookHandler := handler.NewWebhookHandler(processWebhookUseCase)
	mux := router.Setup(healthHandler, userHandler, classHandler, enrollmentHandler, webhookHandler)
	server := NewServer(configConfig, mux)
	return server, nil
}

// wire.go:

func provideMongoDB(cfg *config.Config) (*database.MongoDB, error) {
	return database.NewMongoDB(cfg.Database.MongoURI, cfg.Database.MongoDBName)
}

func provideMongoDatabase(mongodb *database.MongoDB) *mongo.Database {
	return mongodb.Database
}

func provideMongoClient(mongodb *database.MongoDB) *mongo.Client {
	return mongodb.Client
}

func provideUserRepository(db *mongo.Database) repository.UserRepository {
	return mongodb.NewUserRepository(db)
}

func provideClassRepository(db *mongo.Database, client *mongo.Client) repository.ClassRepository {
	return mongodb.NewClassRepository(db, client)
}

func provideEnrollmentRepository(db *mongo.Database) repository.EnrollmentRepository {
	return mongodb.NewEnrollmentRepository(db)
}

func providePaymentRepository(db *mongo.Database) repository.PaymentRepository {
	return mongodb.NewPaymentRepository(db)
}

func provideMercadoPagoClient(cfg *config.Config) *payment2.MercadoPagoClient {
	return payment2.NewMercadoPagoClient(cfg.MercadoPago.AccessToken)
}
